

export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_ERROR = 'ADD_BLOG_ERROR';

export const GET_ALL_BLOG_REQUEST = 'GET_ALL_BLOG_REQUEST';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_ERROR = 'GET_ALL_BLOG_ERROR';